/* Collegamento dell'interfaccia Campo al database Supabase. */
(() => {
  const { createClient } = window.supabase || {};
  const configured = !!(createClient && window.CAMPO_SUPABASE_URL && window.CAMPO_SUPABASE_PUBLISHABLE_KEY);
  const client = configured ? createClient(window.CAMPO_SUPABASE_URL, window.CAMPO_SUPABASE_PUBLISHABLE_KEY) : null;
  const state = { user: null, company: null, season: null, seasons: [], parcels: [], page: 'dashboard' };
  const view = document.getElementById('view');
  const names = { dashboard:'Panoramica', appezzamenti:'Appezzamenti', piano:'Piano colturale', programmazione:'Programmazione operazioni', magazzino:'Magazzino', fitosanitari:'Prodotti fitosanitari', campagna:'Quaderno di campagna', cantina:'Registro di cantina', impostazioni:'Azienda e campagne' };
  const icons = { magazzino:'▤', fitosanitari:'♧', campagna:'▧', cantina:'◉' };
  const esc = value => String(value ?? '').replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const errText = error => error?.message || 'Si è verificato un errore. Riprova.';
  const area = value => Number(value || 0).toLocaleString('it-IT',{minimumFractionDigits:2,maximumFractionDigits:4});
  const dateLabel = value => value ? new Date(value + 'T00:00:00').toLocaleDateString('it-IT') : '—';

  function addStyle(){
    const style=document.createElement('style');
    style.textContent=`.auth-cover{position:fixed;inset:0;z-index:50;background:#f7f8f5;display:grid;place-items:center;padding:20px}.auth-card{width:min(430px,100%);background:#fff;border:1px solid #e7e9e4;border-radius:16px;padding:28px;box-shadow:0 18px 60px #1e352018}.auth-card h1{font-size:23px;margin:0 0 5px}.auth-card p{color:#788078;font-size:13px;margin:0 0 20px}.auth-card .field{margin:13px 0}.auth-card .field input{width:100%;border:1px solid #e7e9e4;border-radius:8px;padding:11px}.auth-error{color:#a43d37;font-size:12px;min-height:18px;margin:10px 0}.auth-card button{width:100%;padding:11px}.cloud-form{padding:20px}.cloud-form h2{margin:0 0 5px;font-size:15px}.cloud-form p{color:#788078;font-size:11px;margin:0 0 16px}.cloud-actions{display:flex;gap:8px;justify-content:flex-end;margin-top:14px}.season-chip{cursor:pointer}.toolbar select{border:1px solid #e7e9e4;background:white;border-radius:8px;padding:9px}.entry-actions{display:flex;justify-content:flex-end;margin-top:12px}.empty-cell{text-align:center;color:#788078;padding:25px!important}`;
    document.head.appendChild(style);
  }
  function ensureCover(){
    addStyle();
    const cover=document.createElement('div');cover.className='auth-cover';cover.id='auth-cover';
    cover.innerHTML=`<form class="auth-card" id="auth-form"><div class="logo" style="margin-bottom:15px">✳</div><h1>Accedi a Campo</h1><p>I tuoi registri aziendali sono protetti e salvati nel tuo archivio.</p><div class="field"><label for="auth-email">Email</label><input id="auth-email" type="email" autocomplete="username" required></div><div class="field"><label for="auth-password">Password</label><input id="auth-password" type="password" autocomplete="current-password" required></div><div class="auth-error" id="auth-error"></div><button class="btn primary" type="submit">Accedi</button></form>`;
    document.body.appendChild(cover);
    cover.querySelector('form').addEventListener('submit', async e=>{
      e.preventDefault();const button=cover.querySelector('button');button.disabled=true;button.textContent='Accesso in corso…';
      const {data,error}=await client.auth.signInWithPassword({email:cover.querySelector('#auth-email').value.trim(),password:cover.querySelector('#auth-password').value});
      button.disabled=false;button.textContent='Accedi';
      if(error){cover.querySelector('#auth-error').textContent='Accesso non riuscito: '+errText(error);return}
      cover.remove();await start(data.user);
    });
    if(!configured){cover.querySelector('#auth-error').textContent='Collegamento al database non configurato. Contatta chi ha preparato l’app.';cover.querySelector('button').disabled=true;}
  }
  async function ensureCompanyAndSeason(){
    let {data:company,error}=await client.from('companies').select('*').eq('owner_id',state.user.id).maybeSingle();
    if(error)throw error;
    if(!company){const result=await client.from('companies').insert({owner_id:state.user.id,name:'La mia azienda'}).select().single();if(result.error)throw result.error;company=result.data;}
    state.company=company;
    let seasons=await client.from('seasons').select('*').eq('company_id',company.id).order('label',{ascending:false});
    if(seasons.error)throw seasons.error;
    state.seasons=seasons.data||[];
    if(!state.seasons.length){const result=await client.from('seasons').insert({company_id:company.id,label:'2026/2027'}).select().single();if(result.error)throw result.error;state.seasons=[result.data];}
    state.season=state.seasons[0];
  }
  async function start(user){
    state.user=user;
    try{await ensureCompanyAndSeason();updateHeader();await go('dashboard');}
    catch(error){notify('Problema nel caricamento: '+errText(error));}
  }
  function updateHeader(){
    const company=state.company?.name||'Azienda agricola';const season=state.season?.label||'—';
    document.querySelectorAll('.sidebottom b').forEach(el=>el.textContent=company);
    document.querySelectorAll('.sidebottom').forEach(el=>{const text=el.childNodes;for(const n of text)if(n.nodeType===3)n.textContent='Campagna '+season+'\n';});
    const crumb=document.querySelector('.crumb');if(crumb)crumb.innerHTML=`${esc(company)} <span style="padding:0 7px;color:#bbb">/</span> <b id="crumb">${esc(names[state.page]||'Panoramica')}</b>`;
    const chip=document.querySelector('.season');if(chip){chip.textContent='◷  Campagna '+season;chip.title='Cambia da Azienda e campagne';chip.onclick=()=>go('impostazioni');}
  }
  async function loadParcels(){const r=await client.from('parcels').select('*').eq('company_id',state.company.id).order('name');if(r.error)throw r.error;state.parcels=r.data||[];return state.parcels;}
  async function go(key){
    state.page=key;document.querySelectorAll('.nav button').forEach(b=>b.classList.toggle('active',b.dataset.page===key));
    const crumb=document.querySelector('.crumb b');if(crumb)crumb.textContent=names[key]||key;
    document.getElementById('sidebar').classList.remove('open');
    view.innerHTML='<div class="card panel">Caricamento dati…</div>';
    try{
      if(key==='dashboard')view.innerHTML=await dashboardPage();
      else if(key==='appezzamenti')view.innerHTML=await parcelPage();
      else if(key==='piano')view.innerHTML=await planPage();
      else if(key==='programmazione')view.innerHTML=await operationsPage();
      else if(key==='impostazioni')view.innerHTML=settingsPage();
      else if(['magazzino','fitosanitari','campagna','cantina'].includes(key))view.innerHTML=await registerPage(key);
      bindPage(key);updateHeader();
    }catch(error){view.innerHTML=`<div class="card panel"><h2>Non riesco a caricare questa sezione</h2><p>${esc(errText(error))}</p><button class="btn" onclick="go('${esc(key)}')">Riprova</button></div>`;}
  }
  async function dashboardPage(){
    const [parcels,ops,entries]=await Promise.all([
      client.from('parcels').select('id,hectares').eq('company_id',state.company.id),
      client.from('field_operations').select('id,status').eq('company_id',state.company.id).eq('season_id',state.season.id),
      client.from('register_entries').select('id,register_type').eq('company_id',state.company.id).eq('season_id',state.season.id)
    ]);for(const r of [parcels,ops,entries])if(r.error)throw r.error;
    const areaTotal=(parcels.data||[]).reduce((a,p)=>a+Number(p.hectares||0),0);
    return `<div class="welcome"><div><h1>${esc(state.company.name)} 👋</h1><p>Riepilogo della campagna ${esc(state.season.label)}.</p></div><div class="actions"><button class="btn" onclick="exportArchive()">⇩ &nbsp;Esporta archivio</button><button class="btn primary" onclick="go('impostazioni')">Impostazioni</button></div></div><div class="grid stats"><div class="card stat"><div class="stathead">Appezzamenti <span class="staticon">▧</span></div><div class="statnum">${(parcels.data||[]).length}</div><div class="statfoot">${area(areaTotal)} ha totali</div></div><div class="card stat"><div class="stathead">Operazioni <span class="staticon">↗</span></div><div class="statnum">${(ops.data||[]).length}</div><div class="statfoot">${(ops.data||[]).filter(x=>x.status==='Completata').length} completate</div></div><div class="card stat"><div class="stathead">Registrazioni <span class="staticon">▤</span></div><div class="statnum">${(entries.data||[]).length}</div><div class="statfoot">In questa campagna</div></div><div class="card stat"><div class="stathead">Campagna <span class="staticon">◷</span></div><div class="statnum" style="font-size:20px">${esc(state.season.label)}</div><div class="statfoot">Archivio online attivo</div></div></div><div class="grid modules"><article class="card module" onclick="go('appezzamenti')"><div class="moduleicon">▧</div><h3>Appezzamenti</h3><p>Terreni, superfici e riferimenti.</p></article><article class="card module" onclick="go('piano')"><div class="moduleicon">▨</div><h3>Piano colturale</h3><p>Colture associate alla campagna.</p></article><article class="card module" onclick="go('programmazione')"><div class="moduleicon">◷</div><h3>Operazioni</h3><p>Programmazione e stato lavori.</p></article>${Object.entries(names).filter(([k])=>['magazzino','fitosanitari','campagna','cantina'].includes(k)).map(([k,n])=>`<article class="card module" onclick="go('${k}')"><div class="moduleicon">${icons[k]}</div><h3>${n}</h3><p>Registro salvato nel database.</p></article>`).join('')}</div>`;
  }
  async function parcelPage(){
    const items=await loadParcels(),total=items.reduce((a,p)=>a+Number(p.hectares||0),0);
    return `<div class="page-title"><div><h1>Appezzamenti</h1><p>Terreni e superfici dell’azienda, salvati online.</p></div></div><div class="parcel-grid"><form class="card cloud-form" id="parcel-form"><h2>Nuovo appezzamento</h2><p>Inserisci i dati principali del terreno.</p><div class="field"><label>Nome appezzamento *</label><input name="name" required maxlength="80" placeholder="Es. Vigneto Nord"></div><div class="formrow"><div class="field"><label>Coltura</label><input name="crop" placeholder="Es. Vite"></div><div class="field"><label>Superficie (ettari) *</label><input name="hectares" type="number" min="0.0001" step="0.0001" required placeholder="Es. 2,5"></div></div><div class="field"><label>Riferimento / note</label><input name="reference" maxlength="120" placeholder="Particella, località"></div><div class="cloud-actions"><button class="btn primary">Salva appezzamento</button></div></form><section class="card parcel-records" style="padding:20px"><h2>I tuoi appezzamenti</h2><p>${items.length} registrati</p><div class="parcel-total">Superficie totale: ${area(total)} ha</div><div class="parcel-records-list">${items.length?items.map(p=>`<div class="parcel-record"><div><strong>${esc(p.name)}</strong><small>${esc(p.crop||'Coltura non indicata')} · ${area(p.hectares)} ha${p.reference?' · '+esc(p.reference):''}</small></div><button class="btn" data-delete-parcel="${p.id}">Rimuovi</button></div>`).join(''):'<div class="parcel-empty">Non hai ancora inserito appezzamenti.</div>'}</div></section></div>`;
  }
  async function plotOptions(){const items=await loadParcels();return items.map(p=>`<option value="${esc(p.id)}">${esc(p.name)}</option>`).join('');}
  async function planPage(){
    const [items,plots]=await Promise.all([client.from('crop_plans').select('*,parcels(name)').eq('company_id',state.company.id).eq('season_id',state.season.id).order('created_at',{ascending:false}),plotOptions()]);if(items.error)throw items.error;
    const rows=items.data||[],total=rows.reduce((a,p)=>a+Number(p.hectares||0),0);
    return `<div class="page-title"><div><h1>Piano colturale</h1><p>Campagna ${esc(state.season.label)} · colture per appezzamento.</p></div></div><div class="planning-grid"><form class="card cloud-form" id="plan-form"><h2>Nuova coltura</h2><p>Associa coltura, superficie e appezzamento.</p><div class="formrow"><div class="field"><label>Appezzamento *</label><select name="parcel_id" required><option value="">Seleziona appezzamento</option>${plots}</select></div><div class="field"><label>Coltura *</label><input name="crop" required placeholder="Es. Grano duro"></div></div><div class="formrow"><div class="field"><label>Varietà</label><input name="variety" placeholder="Es. Senatore Cappelli"></div><div class="field"><label>Superficie (ettari) *</label><input name="hectares" type="number" min="0.0001" step="0.0001" required></div></div><div class="field"><label>Note</label><input name="notes" placeholder="Semina, rotazione, note"></div><div class="cloud-actions"><button class="btn primary">Aggiungi al piano</button></div></form><section class="card planning-list"><h2>Colture pianificate</h2><p>${rows.length} voci · ${area(total)} ha</p><div class="record-list">${rows.length?rows.map(p=>`<article class="record-card"><div class="record-top"><strong>${esc(p.crop)}</strong><span class="tag">${area(p.hectares)} ha</span></div><div class="record-meta">${esc(p.parcels?.name||'Appezzamento')} ${p.variety?'· '+esc(p.variety):''}</div>${p.notes?`<div class="record-note">${esc(p.notes)}</div>`:''}<button class="textlink" data-delete-plan="${p.id}">Rimuovi</button></article>`).join(''):'<div class="parcel-empty">Nessuna coltura pianificata.</div>'}</div></section></div>`;
  }
  async function operationsPage(){
    const [items,plots]=await Promise.all([client.from('field_operations').select('*,parcels(name)').eq('company_id',state.company.id).eq('season_id',state.season.id).order('planned_date'),plotOptions()]);if(items.error)throw items.error;
    const rows=items.data||[];
    return `<div class="page-title"><div><h1>Programmazione operazioni in campo</h1><p>Attività per la campagna ${esc(state.season.label)}.</p></div></div><div class="planning-grid"><form class="card cloud-form" id="operation-form"><h2>Nuova operazione</h2><p>Inserisci quando e dove è previsto il lavoro.</p><div class="formrow"><div class="field"><label>Data prevista *</label><input name="planned_date" type="date" required></div><div class="field"><label>Appezzamento *</label><select name="parcel_id" required><option value="">Seleziona appezzamento</option>${plots}</select></div></div><div class="formrow"><div class="field"><label>Operazione *</label><input name="operation" required placeholder="Es. Potatura"></div><div class="field"><label>Coltura</label><input name="crop" placeholder="Es. Vite"></div></div><div class="formrow"><div class="field"><label>Responsabile</label><input name="responsible"></div><div class="field"><label>Note / attrezzatura</label><input name="notes"></div></div><div class="cloud-actions"><button class="btn primary">Programma operazione</button></div></form><section class="card planning-list"><h2>Operazioni programmate</h2><p>${rows.length} in agenda</p><div class="record-list">${rows.length?rows.map(o=>`<article class="record-card"><div class="record-top"><strong>${esc(o.operation)}</strong><span class="tag ${o.status==='Completata'?'done':''}">${esc(o.status)}</span></div><div class="record-meta">${dateLabel(o.planned_date)} · ${esc(o.parcels?.name||'Appezzamento')}${o.crop?' · '+esc(o.crop):''}</div><div class="record-note">${esc(o.responsible||'')}${o.notes?' · '+esc(o.notes):''}</div><div class="record-actions"><button class="textlink" data-toggle-op="${o.id}">${o.status==='Completata'?'Segna da fare':'Segna completata'}</button><button class="textlink" data-delete-op="${o.id}">Rimuovi</button></div></article>`).join(''):'<div class="parcel-empty">Nessuna operazione in agenda.</div>'}</div></section></div>`;
  }
  async function registerPage(key){
    const result=await client.from('register_entries').select('*').eq('company_id',state.company.id).eq('register_type',key).order('entry_date',{ascending:false});if(result.error)throw result.error;
    const cols=key==='magazzino'?['Data','Movimento / prodotto','Categoria','Quantità','Lotto / posizione','Note']:key==='fitosanitari'?['Data','Prodotto','Attività / principio attivo','Quantità','Lotto / posizione','Note']:key==='campagna'?['Data','Attività','Appezzamento','Prodotto / lavorazione','Operatore','Dettaglio']:['Data','Operazione','Prodotto / partita','Quantità','Vasca / contenitore','Note'];
    const rows=result.data||[];
    return `<div class="page-title"><div><h1>${names[key]}</h1><p>Registrazioni salvate online${key==='campagna'||key==='cantina'?' per la campagna '+esc(state.season.label):''}.</p></div><button class="btn primary" onclick="openCloudEntry('${key}')">＋ &nbsp;${key==='magazzino'?'Registra movimento':key==='fitosanitari'?'Aggiungi prodotto':key==='cantina'?'Registra operazione':'Nuova attività'}</button></div><div class="toolbar"><input class="search" placeholder="⌕ Cerca nel registro…" oninput="filterRows(this.value)"><button class="btn" onclick="exportRegister('${key}')">⇩ &nbsp;Esporta CSV</button></div><div class="card tablewrap"><table class="data-table"><thead><tr>${cols.map(c=>`<th>${c}</th>`).join('')}<th></th></tr></thead><tbody id="rows">${rows.length?rows.map(r=>`<tr><td>${dateLabel(r.entry_date)}</td><td>${esc(r.activity)}</td><td>${esc(r.location||r.product||'—')}</td><td>${esc([r.quantity,r.unit].filter(Boolean).join(' ')||'—')}</td><td>${esc(r.lot||'—')}</td><td>${esc(r.notes||r.operator||'—')}</td><td><button class="textlink" data-delete-entry="${r.id}">Rimuovi</button></td></tr>`).join(''):`<tr><td colspan="7" class="empty-cell">Nessuna registrazione in questo registro.</td></tr>`}</tbody></table></div>`;
  }
  function settingsPage(){return `<div class="page-title"><div><h1>Azienda e campagne</h1><p>Modifica il nome aziendale e imposta la campagna attiva.</p></div></div><form class="card cloud-form" id="company-form" style="max-width:650px"><h2>Dati azienda</h2><div class="field" style="margin-top:15px"><label>Nome azienda</label><input name="name" required value="${esc(state.company.name)}"></div><div class="field" style="margin-top:15px"><label>Campagna agraria attiva</label><select name="season_id">${state.seasons.map(s=>`<option value="${s.id}" ${s.id===state.season.id?'selected':''}>${esc(s.label)}</option>`).join('')}</select></div><div class="formrow"><div class="field"><label>Aggiungi nuova campagna (es. 2027/2028)</label><input name="new_season" placeholder="2027/2028"></div><div class="field" style="display:flex;align-items:end"><button class="btn" type="button" id="add-season">＋ Aggiungi campagna</button></div></div><div class="cloud-actions"><button class="btn primary">Salva impostazioni</button><button class="btn" type="button" id="logout">Esci dall’app</button></div></form><div class="card panel" style="max-width:650px;margin-top:16px"><h2>Esporta dati</h2><p>Scarica una copia dei registri e delle campagne in formato JSON.</p><button class="btn" onclick="exportArchive()">⇩ Esporta archivio completo</button></div>`;}
  function bindPage(key){
    const parcelForm=document.getElementById('parcel-form');if(parcelForm)parcelForm.onsubmit=async e=>{e.preventDefault();const f=new FormData(parcelForm);const r=await client.from('parcels').insert({company_id:state.company.id,name:f.get('name').trim(),crop:f.get('crop').trim()||null,hectares:Number(f.get('hectares')),reference:f.get('reference').trim()||null}).select().single();if(r.error){notify(errText(r.error));return}notify('Appezzamento salvato online.');await go('appezzamenti');};
    view.querySelectorAll('[data-delete-parcel]').forEach(b=>b.onclick=async()=>{if(!confirm('Rimuovere questo appezzamento?'))return;const r=await client.from('parcels').delete().eq('id',b.dataset.deleteParcel).eq('company_id',state.company.id);if(r.error){notify('Non posso rimuovere l’appezzamento: potrebbe essere usato in altri registri.');return}await go('appezzamenti');});
    const plan=document.getElementById('plan-form');if(plan)plan.onsubmit=async e=>{e.preventDefault();const f=new FormData(plan);const r=await client.from('crop_plans').insert({company_id:state.company.id,season_id:state.season.id,parcel_id:f.get('parcel_id'),crop:f.get('crop').trim(),variety:f.get('variety').trim()||null,hectares:Number(f.get('hectares')),notes:f.get('notes').trim()||null});if(r.error){notify(errText(r.error));return}notify('Coltura aggiunta al piano.');await go('piano');};
    view.querySelectorAll('[data-delete-plan]').forEach(b=>b.onclick=async()=>{if(!confirm('Rimuovere questa coltura dal piano?'))return;const r=await client.from('crop_plans').delete().eq('id',b.dataset.deletePlan).eq('company_id',state.company.id);if(r.error)notify(errText(r.error));else await go('piano');});
    const op=document.getElementById('operation-form');if(op)op.onsubmit=async e=>{e.preventDefault();const f=new FormData(op);const r=await client.from('field_operations').insert({company_id:state.company.id,season_id:state.season.id,parcel_id:f.get('parcel_id'),planned_date:f.get('planned_date'),operation:f.get('operation').trim(),crop:f.get('crop').trim()||null,responsible:f.get('responsible').trim()||null,notes:f.get('notes').trim()||null});if(r.error){notify(errText(r.error));return}notify('Operazione salvata online.');await go('programmazione');};
    view.querySelectorAll('[data-toggle-op]').forEach(b=>b.onclick=async()=>{const r=await client.from('field_operations').select('status').eq('id',b.dataset.toggleOp).single();if(r.error){notify(errText(r.error));return}const status=r.data.status==='Completata'?'Programmata':'Completata';const upd=await client.from('field_operations').update({status,completed_at:status==='Completata'?new Date().toISOString():null}).eq('id',b.dataset.toggleOp);if(upd.error)notify(errText(upd.error));else await go('programmazione');});
    view.querySelectorAll('[data-delete-op]').forEach(b=>b.onclick=async()=>{if(!confirm('Rimuovere questa operazione?'))return;const r=await client.from('field_operations').delete().eq('id',b.dataset.deleteOp);if(r.error)notify(errText(r.error));else await go('programmazione');});
    view.querySelectorAll('[data-delete-entry]').forEach(b=>b.onclick=async()=>{if(!confirm('Rimuovere questa registrazione?'))return;const r=await client.from('register_entries').delete().eq('id',b.dataset.deleteEntry);if(r.error)notify(errText(r.error));else await go(key);});
    const companyForm=document.getElementById('company-form');if(companyForm){companyForm.onsubmit=async e=>{e.preventDefault();const f=new FormData(companyForm),chosen=state.seasons.find(s=>s.id===f.get('season_id'));const [c,s]=await Promise.all([client.from('companies').update({name:f.get('name').trim(),updated_at:new Date().toISOString()}).eq('id',state.company.id).select().single(),Promise.resolve({data:chosen})]);if(c.error){notify(errText(c.error));return}state.company=c.data;state.season=s.data;updateHeader();notify('Impostazioni salvate.');await go('impostazioni');};
      document.getElementById('add-season').onclick=async()=>{const value=companyForm.elements.new_season.value.trim();if(!value){notify('Scrivi il nome della nuova campagna.');return}const r=await client.from('seasons').insert({company_id:state.company.id,label:value}).select().single();if(r.error){notify(errText(r.error));return}state.seasons.unshift(r.data);state.season=r.data;notify('Nuova campagna aggiunta.');await go('impostazioni');};
      document.getElementById('logout').onclick=async()=>{await client.auth.signOut();location.reload();};
    }
  }
  window.openCloudEntry=async key=>{
    const overlay=document.getElementById('modalback'),modal=overlay.querySelector('.modal');
    modal.innerHTML=`<div class="modalhead"><h2>${names[key]}</h2><button class="close" type="button" id="cloud-close">×</button></div><p>Inserisci una registrazione. Sarà salvata nel database.</p><form id="entry-form"><div class="formrow"><div class="field"><label>Data *</label><input name="entry_date" type="date" required value="${new Date().toISOString().slice(0,10)}"></div><div class="field"><label>${key==='campagna'?'Attività':'Prodotto / operazione'} *</label><input name="activity" required placeholder="Descrizione"></div></div><div class="formrow"><div class="field"><label>Appezzamento, categoria o contenitore</label><input name="location" placeholder="Facoltativo"></div><div class="field"><label>Quantità</label><input name="quantity" type="number" step="0.0001" placeholder="Es. 12"></div></div><div class="formrow"><div class="field"><label>Unità / lotto</label><input name="unit" placeholder="kg, L, pezzi"></div><div class="field"><label>Operatore</label><input name="operator"></div></div><div class="field"><label>Note</label><input name="notes"></div><div class="modalfoot"><button class="btn" type="button" id="cloud-cancel">Annulla</button><button class="btn primary">Salva registrazione</button></div></form>`;
    overlay.classList.add('show');const close=()=>overlay.classList.remove('show');modal.querySelector('#cloud-close').onclick=close;modal.querySelector('#cloud-cancel').onclick=close;
    modal.querySelector('#entry-form').onsubmit=async e=>{e.preventDefault();const f=new FormData(e.currentTarget);const result=await client.from('register_entries').insert({company_id:state.company.id,season_id:state.season.id,register_type:key,entry_date:f.get('entry_date'),activity:f.get('activity').trim(),product:f.get('activity').trim(),location:f.get('location').trim()||null,quantity:f.get('quantity')?Number(f.get('quantity')):null,unit:f.get('unit').trim()||null,lot:f.get('unit').trim()||null,operator:f.get('operator').trim()||null,notes:f.get('notes').trim()||null});if(result.error){notify(errText(result.error));return}close();notify('Registrazione salvata online.');await go(key);};
  };
  window.openModal=()=>notify('Per inserire dati usa il pulsante “Nuova registrazione” nel registro desiderato.');
  function csvDownload(filename,rows){const csv=rows.map(row=>row.map(v=>'"'+String(v??'').replace(/"/g,'""')+'"').join(';')).join('\r\n');const a=document.createElement('a');a.href=URL.createObjectURL(new Blob(['\ufeff'+csv],{type:'text/csv;charset=utf-8'}));a.download=filename;a.click();URL.revokeObjectURL(a.href);}
  window.exportRegister=async key=>{const r=await client.from('register_entries').select('*').eq('company_id',state.company.id).eq('register_type',key).order('entry_date');if(r.error){notify(errText(r.error));return}csvDownload(key+'-'+state.season.label+'.csv',[['Data','Tipo','Attività','Prodotto','Quantità','Unità','Lotto','Posizione','Operatore','Note'],...(r.data||[]).map(x=>[x.entry_date,key,x.activity,x.product,x.quantity,x.unit,x.lot,x.location,x.operator,x.notes])]);};
  window.exportArchive=async()=>{try{const names=['seasons','parcels','crop_plans','field_operations','register_entries'];const data={azienda:state.company,campagna_attiva:state.season,esportato_il:new Date().toISOString(),dati:{}};for(const table of names){let q=client.from(table).select('*').eq('company_id',state.company.id);if(table==='crop_plans'||table==='field_operations')q=q.eq('season_id',state.season.id);if(table==='register_entries')q=q.eq('season_id',state.season.id);const r=await q;if(r.error)throw r.error;data.dati[table]=r.data||[]}const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([JSON.stringify(data,null,2)],{type:'application/json'}));a.download='campo-'+state.season.label.replace('/','-')+'.json';a.click();URL.revokeObjectURL(a.href);}catch(error){notify(errText(error));}};
  window.go=go;
  window.filterRows=q=>document.querySelectorAll('#rows tr').forEach(tr=>tr.style.display=tr.textContent.toLowerCase().includes(q.toLowerCase())?'':'none');
  document.querySelectorAll('.nav button').forEach(button=>{if(button.dataset.page==='impostazioni')return;});
  const settingsButton=document.createElement('button');settingsButton.dataset.page='impostazioni';settingsButton.innerHTML='<span class="ico">⚙</span>Azienda e campagne';document.getElementById('nav').appendChild(settingsButton);
  document.getElementById('save').onclick=()=>notify('Apri il registro desiderato e scegli “Nuova registrazione”.');
  ensureCover();
  if(configured)client.auth.getSession().then(({data,error})=>{if(error){document.getElementById('auth-error').textContent=errText(error);return}if(data.session){document.getElementById('auth-cover')?.remove();start(data.session.user);}});
})();
